name: manga_remind
description: A manga reminder application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.2"
  shared_preferences: "0.5.3+4"
  json_serializable: ^3.1.0
  dotted_border: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"

flutter:
  fonts:
    - family: GochiHand
      fonts:
        - asset: assets/fonts/GochiHand-Regular.ttf
    - family: Mangas
      fonts:
        - asset: assets/fonts/animeace.ttf
    - family: Deathnote
      fonts:
        - asset: assets/fonts/deathnote.ttf
  uses-material-design: true