name: manga_remind
description: A manga reminder application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: AnimeAce
      fonts:
        - asset: fonts/animeace.ttf
    - family: GochiHand
      fonts:
        - asset: fonts/GochiHand-Regular.ttf
  uses-material-design: true